extends:
  - standard-with-typescript
  - prettier

ignorePatterns:
  - node_modules
  - dist
rules:
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: false
        orderImportKind: asc
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
  curly:
    - error
    - all
  no-unused-vars:
    - error
    - args: none
  no-console:
    - error
    - allow:
        - warn
        - error
        - info
        - debug
  no-irregular-whitespace:
    - error
    - skipStrings: true
      skipComments: false
      skipRegExps: false
      skipTemplates: true
