'src/**/*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
  - 'prettier --log-level warn --cache --cache-location ./node_modules/.cache/.prettier-cache --write'

'src/**/*.{scss,css}':
  - 'stylelint --cache --cache-location ./node_modules/.cache/.stylelintcache --fix'
  - 'prettier --log-level warn --cache --cache-location ./node_modules/.cache/.prettier-cache --write'

'*.{json,yml,yaml}':
  - 'prettier --log-level warn --cache --cache-location ./node_modules/.cache/.prettier-cache --write'
